---
dist: xenial

matrix:
  include:
    # Test suite for the application itself
    - language: python
      python: "3.7"

      cache: pip

      env:
        - SECRET_KEY=test

      install:
        - pip install --upgrade pip
        - pip install --upgrade pipenv
        - pipenv sync --dev

      script:
        - ./docs/check-requirements.sh docs/requirements.txt
        - pipenv run black --check .
        - pipenv run flake8
        - pipenv run coverage run -m pytest ultimanager/
        - pipenv run pytest ultimanager/functional_tests

      after_success:
        - pipenv run codecov

    # Test building the docker image
    - language: minimal

      services:
        - docker

      script:
        - docker build -t ultimanager-api .


notifications:
  email:
    on_failure: always
    on_success: never
