---
dist: xenial
language: python
python: "3.7"

cache: pip

env:
  global:
    - SECRET_KEY=test


install:
  - pip install --upgrade pip
  - pip install --upgrade pipenv
  - pipenv sync --dev

script:
  - pipenv run black --check .
  - pipenv run flake8


notifications:
  email:
    on_failure: always
    on_success: never
