# Generated by Django 2.2.1 on 2019-05-10 13:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="A unique identifier for the instance.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text=(
                            "The date and time of the object's creation."
                        ),
                        verbose_name="creation time",
                    ),
                ),
                (
                    "time_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text=(
                            "The date and time of the last update made to the "
                            "object."
                        ),
                        verbose_name="last update time",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text=(
                            "A unique identifier for the instance derived "
                            "from the name of the instance."
                        ),
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Any additional notes about the team.",
                        verbose_name="description",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the team.",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
            ],
            options={
                "verbose_name": "team",
                "verbose_name_plural": "teams",
                "ordering": ("-time_created",),
                "abstract": False,
            },
        )
    ]
